name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  pdf: ^3.10.0
  path_provider: ^2.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  # (removed flutter_contacts and permission_handler to avoid build issues in this environment)

dev_dependencies:
        flutter_launcher_icons: ^0.13.1 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter_test:
    sdk: flutter
flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
    - assets/images/logo.jpg